export const makes = [
  ["1", "Toyota"],
  ["31", "Audi"],
  ["3", "BMW"],
  ["4", "Chevrolet"],
  ["5", "Daihatsu"],
  ["6", "Ford"],
  ["7", "Haval"],
  ["8", "Honda"],
  ["9", "Hyundai"],
  ["10", "Isuzu"],
  ["29", "Jaguar"],
  ["11", "Jeep"],
  ["13", "Kia"],
  ["14", "Land Rover"],
  ["15", "Lexus"],
  ["16", "Mahindra"],
  ["17", "Mazda"],
  ["18", "Mercedes-Benz"],
  ["19", "Mitsubishi"],
  ["20", "Nissan"],
  ["21", "Opel"],
  ["28", "Peugeot"],
  ["22", "Renault"],
  ["23", "Subaru"],
  ["24", "Suzuki"],
  ["25", "TATA"],
  ["26", "Volkswagen"],
  ["27", "Volvo"],
] as const;
const img = (name: string) => `/images/vehicles/${name}`;
export const vehicles = [
  {
    id: "6",
    makeId: "1",
    make: "Toyota",
    name: "Hilux",
    image: "/images/hilux-road.webp",
    intro:
      "A durable pickup known across Zimbabwe for work, travel and demanding road conditions.",
  },
  {
    id: "17",
    makeId: "1",
    make: "Toyota",
    name: "Passo",
    image: img("model_20210715144932.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "18",
    makeId: "1",
    make: "Toyota",
    name: "Allion",
    image: img("model_20210717152440.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "19",
    makeId: "1",
    make: "Toyota",
    name: "Belta",
    image: img("model_20210717155700.png"),
    intro: "A compact saloon with practical everyday usability.",
  },
  {
    id: "20",
    makeId: "1",
    make: "Toyota",
    name: "Wish",
    image: img("model_20210717163425.png"),
    intro: "A versatile people mover with flexible cabin space.",
  },
  {
    id: "21",
    makeId: "1",
    make: "Toyota",
    name: "Camry",
    image: img("model_20210720111708.png"),
    intro: "A refined saloon balancing comfort and dependable ownership.",
  },
  {
    id: "22",
    makeId: "1",
    make: "Toyota",
    name: "Mark X",
    image: "/images/vehicles/pinterest-mark-x.jpg",
    intro:
      "A rear-wheel-drive sports saloon with a strong following in Zimbabwe.",
  },
  {
    id: "11",
    makeId: "31",
    make: "Audi",
    name: "A4",
    image: img("model_20210714121802.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "12",
    makeId: "3",
    make: "BMW",
    name: "3 Series",
    image: img("model_20210714125741.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "23",
    makeId: "3",
    make: "BMW",
    name: "1 Series",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "24",
    makeId: "3",
    make: "BMW",
    name: "5 Series",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "25",
    makeId: "3",
    make: "BMW",
    name: "7 Series",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "13",
    makeId: "8",
    make: "Honda",
    name: "Fit “Small is the New Big”",
    image: img("model_20210714175721.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "14",
    makeId: "8",
    make: "Honda",
    name: "Freed",
    image: img("model_20210714181913.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "15",
    makeId: "8",
    make: "Honda",
    name: "Airwave",
    image: img("model_20210715125734.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "16",
    makeId: "8",
    make: "Honda",
    name: "CR-V",
    image: img("model_20210715134831.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "26",
    makeId: "8",
    make: "Honda",
    name: "FR-V Edix",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "27",
    makeId: "9",
    make: "Hyundai",
    name: "Santa Fe",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "28",
    makeId: "9",
    make: "Hyundai",
    name: "Tucson",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "29",
    makeId: "9",
    make: "Hyundai",
    name: "Creta",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "30",
    makeId: "9",
    make: "Hyundai",
    name: "Elantra",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "38",
    makeId: "13",
    make: "Kia",
    name: "Sportage",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "39",
    makeId: "13",
    make: "Kia",
    name: "Rio",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "40",
    makeId: "13",
    make: "Kia",
    name: "Picanto",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "41",
    makeId: "13",
    make: "Kia",
    name: "Seltos",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "42",
    makeId: "13",
    make: "Kia",
    name: "Sorento",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "31",
    makeId: "17",
    make: "Mazda",
    name: "BT-50",
    intro: "A capable pickup engineered for utility and long-distance use.",
  },
  {
    id: "32",
    makeId: "17",
    make: "Mazda",
    name: "323",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "33",
    makeId: "17",
    make: "Mazda",
    name: "Mazda6 Atenza",
    intro: "A confident executive saloon with engaging road manners.",
  },
  {
    id: "35",
    makeId: "17",
    make: "Mazda",
    name: "Mazda3 Axela",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "36",
    makeId: "17",
    make: "Mazda",
    name: "B Series",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "37",
    makeId: "17",
    make: "Mazda",
    name: "Mazda2 Demio",
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "43",
    makeId: "18",
    make: "Mercedes-Benz",
    name: "C-Class",
    image: img("model_20211123143220.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "44",
    makeId: "18",
    make: "Mercedes-Benz",
    name: "E-Class",
    image: img("model_20211125133351.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "45",
    makeId: "18",
    make: "Mercedes-Benz",
    name: "S-Class",
    image: img("model_20211125161420.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "46",
    makeId: "18",
    make: "Mercedes-Benz",
    name: "B-Class",
    image: img("model_20211125174746.jpg"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "47",
    makeId: "20",
    make: "Nissan",
    name: "Tiida Latio",
    image: img("model_20211201103105.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "48",
    makeId: "20",
    make: "Nissan",
    name: "Note",
    image: img("model_20211201130249.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "49",
    makeId: "20",
    make: "Nissan",
    name: "Juke",
    image: img("model_20211201134151.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "51",
    makeId: "20",
    make: "Nissan",
    name: "March / Micra",
    image: img("model_20211201142058.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
  {
    id: "52",
    makeId: "20",
    make: "Nissan",
    name: "Sylphy Bluebird",
    image: img("model_20211202144659.png"),
    intro: "Autoheads vehicle guide and ownership information.",
  },
] as const;
export const categories = [
  "Air Freshener",
  "Alternator",
  "ATF",
  "Ball Joints",
  "Batteries",
  "Bearings",
  "Belts and Hoses",
  "Body Parts",
  "Bolts and Nuts",
  "Brake Pads",
  "Canopy",
  "Clutch",
  "Computer Box",
  "Control Arms",
  "CV Joints",
  "CVT Oil",
  "Dashboard Spray",
  "Diagnostics",
  "Engine Coolant",
  "Engine Spares",
  "Filters",
  "Fuel Pump",
  "Gaskets",
  "Grease",
  "Injectors",
  "Jacks",
  "Lamps and Bulbs",
  "Lubricants",
  "Mag Wheels",
  "Mountings",
  "Radiator",
  "Radio and Sound",
  "Reflectors",
  "Seals",
  "Seat Covers",
  "Silicone",
  "Spanners",
  "Spark Plugs",
  "Starter",
  "Suspension",
  "Tools",
  "Transmission",
  "Turbocharger",
  "Tyres",
  "Windscreen",
  "Wipers",
];
export const shops = [
  {
    name: "hp lubes",
    tags: ["Lubricants", "Filters"],
    address: "6 Barking Road, Willowvale, Harare",
    phone: "0772226994",
  },
  {
    name: "FUCHS Zimbabwe",
    tags: ["Lubricants", "Filters", "Batteries"],
    address: "19 Paisley Road, Southerton, Harare",
    phone: "0242751304",
  },
  {
    name: "Global Tyres",
    tags: ["Tyres", "Wheel Alignment", "Batteries"],
    address: "5 Kaguvi",
    phone: "0772419968",
  },
  {
    name: "3 Way",
    tags: ["Lubricants", "Filters", "Brake Pads"],
    address: "5 Kelvin Road North, Graniteside",
    phone: "(024) 275",
  },
  {
    name: "Trooper Canvas",
    tags: ["Seat Covers", "Canopy"],
    address: "9 Lisburn Road, Workington",
    phone: "(024) 275",
  },
  {
    name: "Victor Onions",
    tags: ["Batteries"],
    address: "18 Edison Crescent, Graniteside",
    phone: "(024) 275",
  },
  {
    name: "Exide Express",
    tags: ["Batteries"],
    address: "Motorcity Complex, Seke Road, Graniteside",
    phone: "(024) 277",
  },
  {
    name: "The Battery Centre",
    tags: ["Batteries"],
    address: "172 Samora Machel Avenue, Eastlea",
    phone: "(024) 225",
  },
  {
    name: "Engen Zimbabwe",
    tags: ["Lubricants", "Fuel"],
    address: "71 Kaguvi Street, Harare",
    phone: "0867",
  },
  {
    name: "Drum City",
    tags: ["Engine Spares", "Transmission", "Suspension"],
    address: "859 Bignell Road, New Ardbennie",
    phone: "(024) 266",
  },
];
export const workshopCategories = [
  "Airconditioning",
  "Alarm and Security",
  "Auto Diagnostics",
  "Auto Electrics",
  "Battery",
  "Brake and Clutch",
  "Breakdown and Towing",
  "Car Wash",
  "Engine Overhaul",
  "Engine Tuning and Performance",
  "Exhaust",
  "Gearbox and Transmission",
  "Panelbeating and Spray Painting",
  "Suspension and Steering",
  "Tyres",
  "Vehicle Service",
  "Wheel Alignment",
  "Windscreen",
];
export const mechanics = [
  {
    name: "Landel Motors",
    tags: ["Engine Overhaul", "Vehicle Service", "Auto Electrics"],
    address: "483 Birmingham Road",
    phone: "263773936139",
  },
  {
    name: "Nkhoma",
    tags: ["Gearbox and Transmission"],
    address: "2344 Tecoma",
    phone: "0772755204",
  },
  {
    name: "Lloyd",
    tags: ["Exhaust", "Engine Tuning and Performance"],
    address: "20 Longlands",
    phone: "0783853675",
  },
  {
    name: "Auto Diagnostics & Repair Centre",
    tags: ["Auto Diagnostics"],
    address: "96 George Silundika",
    phone: "0772608210",
  },
  {
    name: "Rollem Motors",
    tags: ["Auto Diagnostics", "Lubricants"],
    address: "18 Bessemer Road",
    phone: "(024) 2706866",
  },
  {
    name: "Ruva",
    tags: ["Engine Overhaul", "Brake and Clutch", "Suspension and Steering"],
    address: "2330 Lower Paradise, Marondera",
    phone: "+263772275754",
  },
];
export const posts = [
  {
    id: "5",
    title: "Castrol Introduces New Automotive Oil Packaging",
    category: "Products and Brands",
    excerpt:
      "Castrol, represented in Zimbabwe by High Performance Lubes, introduces refreshed packaging.",
    image: "/images/castrol.png",
  },
  {
    id: "1",
    title: "Castrol CRB Multi 15W/40",
    category: "Products and Brands",
    excerpt: "A closer look at a familiar heavy-duty lubricant product.",
    image: "/images/castrol.png",
  },
];
export const additionalShops = [
  "Oil Centre Zimbabwe",
  "Easyparts",
  "Techmart",
  "Windscreen Centre",
  "Goldwagen",
  "Electrosales",
  "Oncerun Motors",
  "ME Parts",
  "Autocheck Systems",
  "Plawn Motors",
  "Big Sky Supplies",
  "Auto Medic Body Shop",
  "Hoist Auto",
  "Blackbox Investments",
  "Braford Lubricants",
  "Global Lubricants Zimbabwe",
  "Zuva Valvoline",
  "Peniel Motors",
  "Saboti Trading",
  "Solatek",
  "Tyteslot",
  "PUMA LUBRICANTS",
  "Zim Japan",
  "Budget Motor Parts",
  "Kar Torque",
  "Chase Motors",
  "GTR Auto",
  "Elvan Incorporation",
  "Auto Bros",
  "Tiron Motors",
].map((name) => ({ name, tags: [] as string[], address: "", phone: "" }));
export const allShops = [...shops, ...additionalShops];
